# Load .profile, containing login, non-bash related initializations.
source ~/.profile
 
# Load .bashrc, containing non-login related bash initializations.
source ~/.bashrc

[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*
